export const cropMapping = {
  // --- FRUITS ---
  "mango": "Fruits",
  "alphonso mango": "Fruits",
  "kesar mango": "Fruits",
  "totapuri mango": "Fruits",
  "dasheri mango": "Fruits",
  "apple": "Fruits",
  "shimla apple": "Fruits",
  "kashmir apple": "Fruits",
  "banana": "Fruits",
  "robusta banana": "Fruits",
  "yelakki banana": "Fruits",
  "orange": "Fruits",
  "nagpur orange": "Fruits",
  "grapes": "Fruits",
  "black grapes": "Fruits",
  "green grapes": "Fruits",
  "pomegranate": "Fruits",
  "guava": "Fruits",
  "papaya": "Fruits",
  "watermelon": "Fruits",
  "muskmelon": "Fruits",
  "pineapple": "Fruits",
  "coconut": "Fruits",
  "jackfruit": "Fruits",
  "litchi": "Fruits",
  "kiwi": "Fruits",
  "pear": "Fruits",
  "peach": "Fruits",
  "plum": "Fruits",
  "strawberry": "Fruits",
  "fig": "Fruits",
  "custard apple": "Fruits",
  "sapota": "Fruits",
  "chikoo": "Fruits",
  "cherry": "Fruits",
  "blackberry": "Fruits",
  "blueberry": "Fruits",
  "cranberry": "Fruits",
  "raspberry": "Fruits",
  "avocado": "Fruits",
  "apricot": "Fruits",
  "lemon": "Fruits",
  "lime": "Fruits",
  "sweet lime": "Fruits",
  "mosambi": "Fruits",
  "pomelo": "Fruits",
  "dragon fruit": "Fruits",
  "passion fruit": "Fruits",
  "mulberry": "Fruits",
  "tamarillo": "Fruits",
  "date fruit": "Fruits",
  "olive": "Fruits",

  // --- VEGETABLES ---
  "tomato": "Vegetables",
  "potato": "Vegetables",
  "onion": "Vegetables",
  "red onion": "Vegetables",
  "white onion": "Vegetables",
  "brinjal": "Vegetables",
  "eggplant": "Vegetables",
  "cabbage": "Vegetables",
  "cauliflower": "Vegetables",
  "carrot": "Vegetables",
  "radish": "Vegetables",
  "beetroot": "Vegetables",
  "capsicum": "Vegetables",
  "bell pepper": "Vegetables",
  "spinach": "Vegetables",
  "cucumber": "Vegetables",
  "bottle gourd": "Vegetables",
  "pumpkin": "Vegetables",
  "beans": "Vegetables",
  "french beans": "Vegetables",
  "green peas": "Vegetables",
  "garlic": "Vegetables",
  "ginger": "Vegetables",
  "okra": "Vegetables",
  "lady finger": "Vegetables",
  "bhindi": "Vegetables",
  "bitter gourd": "Vegetables",
  "karela": "Vegetables",
  "ridge gourd": "Vegetables",
  "snake gourd": "Vegetables",
  "sweet potato": "Vegetables",
  "broccoli": "Vegetables",
  "zucchini": "Vegetables",
  "turnip": "Vegetables",
  "drumstick": "Vegetables",
  "ivy gourd": "Vegetables",
  "pointed gourd": "Vegetables",
  "ash gourd": "Vegetables",
  "colocasia": "Vegetables",
  "taro": "Vegetables",
  "yam": "Vegetables",
  "asparagus": "Vegetables",
  "celery": "Vegetables",
  "lettuce": "Vegetables",
  "fenugreek leaves": "Vegetables",
  "methi leaves": "Vegetables",
  "coriander leaves": "Vegetables",
  "mint leaves": "Vegetables",
  "brussels sprouts": "Vegetables",
  "kale": "Vegetables",

  // --- GRAINS ---
  "rice": "Grains",
  "basmati rice": "Grains",
  "paddy": "Grains",
  "wheat": "Grains",
  "sharbati wheat": "Grains",
  "maize": "Grains",
  "corn": "Grains",
  "sweet corn": "Grains",
  "jowar": "Grains",
  "sorghum": "Grains",
  "bajra": "Grains",
  "pearl millet": "Grains",
  "ragi": "Grains",
  "finger millet": "Grains",
  "barley": "Grains",
  "oats": "Grains",
  "rye": "Grains",
  "quinoa": "Grains",
  "spelt": "Grains",
  "millet": "Grains",
  "foxtail millet": "Grains",
  "kodo millet": "Grains",
  "buckwheat": "Grains",
  "amaranth": "Grains",

  // --- PULSES ---
  "toor": "Pulses",
  "toor dal": "Pulses",
  "tur": "Pulses",
  "tur dal": "Pulses",
  "moong": "Pulses",
  "moong dal": "Pulses",
  "urad": "Pulses",
  "urad dal": "Pulses",
  "masoor": "Pulses",
  "masoor dal": "Pulses",
  "chana": "Pulses",
  "chana dal": "Pulses",
  "chickpea": "Pulses",
  "chickpeas": "Pulses",
  "kabuli chana": "Pulses",
  "rajma": "Pulses",
  "kidney beans": "Pulses",
  "peas": "Pulses",
  "dry peas": "Pulses",
  "lentil": "Pulses",
  "lentils": "Pulses",
  "black eyed peas": "Pulses",
  "cowpeas": "Pulses",
  "horse gram": "Pulses",
  "bengal gram": "Pulses",
  "green gram": "Pulses",
  "black gram": "Pulses",

  // --- OIL SEEDS ---
  "soybean": "Oil Seeds",
  "soyabean": "Oil Seeds",
  "groundnut": "Oil Seeds",
  "peanut": "Oil Seeds",
  "mustard": "Oil Seeds",
  "mustard seeds": "Oil Seeds",
  "sunflower seeds": "Oil Seeds",
  "sesame": "Oil Seeds",
  "sesame seeds": "Oil Seeds",
  "til": "Oil Seeds",
  "castor": "Oil Seeds",
  "castor seeds": "Oil Seeds",
  "linseed": "Oil Seeds",
  "flaxseed": "Oil Seeds",
  "safflower": "Oil Seeds",
  "rapeseed": "Oil Seeds",
  "cottonseed": "Oil Seeds",

  // --- CASH CROPS ---
  "cotton": "Cash Crops",
  "sugarcane": "Cash Crops",
  "tobacco": "Cash Crops",
  "jute": "Cash Crops",
  "rubber": "Cash Crops",
  "tea": "Cash Crops",
  "coffee": "Cash Crops",
  "cocoa": "Cash Crops",
  "areca nut": "Cash Crops",
  "betel nut": "Cash Crops",

  // --- SPICES ---
  "turmeric": "Spices",
  "haldi": "Spices",
  "chilli": "Spices",
  "chili": "Spices",
  "red chilli": "Spices",
  "green chilli": "Spices",
  "black pepper": "Spices",
  "cardamom": "Spices",
  "elaichi": "Spices",
  "clove": "Spices",
  "laung": "Spices",
  "cinnamon": "Spices",
  "dalchini": "Spices",
  "coriander powder": "Spices",
  "coriander seeds": "Spices",
  "cumin": "Spices",
  "jeera": "Spices",
  "fenugreek seeds": "Spices",
  "methi seeds": "Spices",
  "fennel": "Spices",
  "saunf": "Spices",
  "star anise": "Spices",
  "nutmeg": "Spices",
  "jaiphal": "Spices",
  "mace": "Spices",
  "javitri": "Spices",
  "tamarind": "Spices",
  "asafoetida": "Spices",
  "hing": "Spices",
  "saffron": "Spices",
  "kesar": "Spices",
  "ginger powder": "Spices",
  "garlic powder": "Spices",

  // --- FLOWERS ---
  "rose": "Flowers",
  "marigold": "Flowers",
  "jasmine": "Flowers",
  "lotus": "Flowers",
  "sunflower": "Flowers",
  "lily": "Flowers",
  "hibiscus": "Flowers",
  "orchid": "Flowers",
  "tulip": "Flowers",
  "carnation": "Flowers",
  "chrysanthemum": "Flowers",
  "lavender": "Flowers",
  "gerbera": "Flowers",
  "anthurium": "Flowers",
  "mogra": "Flowers",

  // --- HERBS ---
  "mint": "Herbs",
  "tulsi": "Herbs",
  "basil": "Herbs",
  "lemongrass": "Herbs",
  "aloe vera": "Herbs",
  "rosemary": "Herbs",
  "thyme": "Herbs",
  "oregano": "Herbs",
  "parsley": "Herbs",
  "sage": "Herbs",
  "dill": "Herbs",

  // --- DRY FRUITS ---
  "almond": "Dry Fruits",
  "badam": "Dry Fruits",
  "cashew": "Dry Fruits",
  "kaju": "Dry Fruits",
  "walnut": "Dry Fruits",
  "akhrot": "Dry Fruits",
  "pistachio": "Dry Fruits",
  "pista": "Dry Fruits",
  "raisin": "Dry Fruits",
  "kishmish": "Dry Fruits",
  "dates": "Dry Fruits",
  "khajour": "Dry Fruits",
  "dried fig": "Dry Fruits",
  "anjeer": "Dry Fruits",
  "prunes": "Dry Fruits",
  "dried apricot": "Dry Fruits",

  // --- PLANTATION CROPS ---
  "tea leaves": "Plantation Crops",
  "coffee beans": "Plantation Crops",
  "rubber latex": "Plantation Crops",
  "cocoa beans": "Plantation Crops",
  "cardamom pods": "Plantation Crops",
  "arecanut palm": "Plantation Crops",

  // --- MEDICINAL PLANTS ---
  "neem": "Medicinal Plants",
  "ashwagandha": "Medicinal Plants",
  "amla": "Medicinal Plants",
  "giloy": "Medicinal Plants",
  "brahmi": "Medicinal Plants",
  "shatavari": "Medicinal Plants",
  "stevia": "Medicinal Plants",
  "sarpagandha": "Medicinal Plants",
  "kalmegh": "Medicinal Plants",
  "safed musli": "Medicinal Plants",

  // --- FODDER CROPS ---
  "alfalfa": "Fodder Crops",
  "clover": "Fodder Crops",
  "sorghum fodder": "Fodder Crops",
  "maize fodder": "Fodder Crops",
  "napier grass": "Fodder Crops",
  "guinea grass": "Fodder Crops",
  "berseem": "Fodder Crops",
  "sudan grass": "Fodder Crops",

  // --- ORGANIC PRODUCTS ---
  "organic fertilizer": "Organic Products",
  "organic compost": "Organic Products",
  "organic manure": "Organic Products",
  "vermicompost": "Organic Products",
  "biofertilizer": "Organic Products",
  "panchagavya": "Organic Products",
  "neem cake": "Organic Products",
  "organic pest control": "Organic Products",
  "organic seeds": "Organic Products",
  "compost": "Organic Products",
  "manure": "Organic Products"
};
